import { defineConfig } from "vitepress"
import { groupIconMdPlugin, groupIconVitePlugin } from "vitepress-plugin-group-icons"

export default defineConfig({
    base: "/string/",
    description: "Functional utilities for strings.",
    title: "string",
    markdown: {
        theme: {
            dark: "catppuccin-macchiato",
            light: "github-light-default",
        },
        config(md) {
            md.use(groupIconMdPlugin)
        },
    },
    themeConfig: {
        aside: false,
        outline: "deep",
        docFooter: {
            next: false,
            prev: false,
        },
        search: {
            provider: "local",
        },
        sidebar: [
            {
                base: "/String/",
                text: "String",
                items: [
                    { link: "create", text: "create" },
                    { link: "append", text: "append" },
                    { link: "camelCase", text: "camelCase" },
                    { link: "capitalize", text: "capitalize" },
                    { link: "constantCase", text: "constantCase" },
                    { link: "drop", text: "drop" },
                    { link: "dropLast", text: "dropLast" },
                    { link: "empty", text: "empty" },
                    { link: "endsWith", text: "endsWith" },
                    { link: "has", text: "has" },
                    { link: "hasAll", text: "hasAll" },
                    { link: "hasAny", text: "hasAny" },
                    { link: "hasNone", text: "hasNone" },
                    { link: "indexOf", text: "indexOf" },
                    { link: "indexOfOr", text: "indexOfOr" },
                    { link: "indexOfOrElse", text: "indexOfOrElse" },
                    { link: "indexOfOrThrow", text: "indexOfOrThrow" },
                    { link: "is", text: "is" },
                    { link: "isEmpty", text: "isEmpty" },
                    { link: "kebabCase", text: "kebabCase" },
                    { link: "lastIndexOf", text: "lastIndexOf" },
                    { link: "lastIndexOfOr", text: "lastIndexOfOr" },
                    { link: "lastIndexOfOrElse", text: "lastIndexOfOrElse" },
                    { link: "lastIndexOfOrThrow", text: "lastIndexOfOrThrow" },
                    { link: "length", text: "length" },
                    { link: "lowerCase", text: "lowerCase" },
                    { link: "match", text: "match" },
                    { link: "matchOr", text: "matchOr" },
                    { link: "matchOrElse", text: "matchOrElse" },
                    { link: "matchOrThrow", text: "matchOrThrow" },
                    { link: "padEnd", text: "padEnd" },
                    { link: "padStart", text: "padStart" },
                    { link: "parseFloat", text: "parseFloat" },
                    { link: "parseFloatOr", text: "parseFloatOr" },
                    { link: "parseFloatOrElse", text: "parseFloatOrElse" },
                    { link: "parseFloatOrThrow", text: "parseFloatOrThrow" },
                    { link: "parseInt", text: "parseInt" },
                    { link: "parseIntOr", text: "parseIntOr" },
                    { link: "parseIntOrElse", text: "parseIntOrElse" },
                    { link: "parseIntOrThrow", text: "parseIntOrThrow" },
                    { link: "pascalCase", text: "pascalCase" },
                    { link: "prepend", text: "prepend" },
                    { link: "repeat", text: "repeat" },
                    { link: "replace", text: "replace" },
                    { link: "replaceAll", text: "replaceAll" },
                    { link: "reverse", text: "reverse" },
                    { link: "slice", text: "slice" },
                    { link: "snakeCase", text: "snakeCase" },
                    { link: "split", text: "split" },
                    { link: "startsWith", text: "startsWith" },
                    { link: "take", text: "take" },
                    { link: "takeLast", text: "takeLast" },
                    { link: "test", text: "test" },
                    { link: "titleCase", text: "titleCase" },
                    { link: "trim", text: "trim" },
                    { link: "trimEnd", text: "trimEnd" },
                    { link: "trimStart", text: "trimStart" },
                    { link: "uncapitalize", text: "uncapitalize" },
                    { link: "upperCase", text: "upperCase" },
                ],
            },
        ],
        socialLinks: [
            { icon: "github", link: "https://github.com/MichaelOstermann/string" },
        ],
    },
    vite: {
        plugins: [
            groupIconVitePlugin(),
        ],
    },
})
