// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { append } from "./append.js";
import { camelCase } from "./camelCase.js";
import { capitalize } from "./capitalize.js";
import { constantCase } from "./constantCase.js";
import { create } from "./create.js";
import { deburr } from "./deburr.js";
import { drop } from "./drop.js";
import { dropLast } from "./dropLast.js";
import { endsWith } from "./endsWith.js";
import { graphemes } from "./graphemes.js";
import { has } from "./has.js";
import { hasAll } from "./hasAll.js";
import { hasAny } from "./hasAny.js";
import { hasNone } from "./hasNone.js";
import { indexOf } from "./indexOf.js";
import { indexOfOr } from "./indexOfOr.js";
import { indexOfOrElse } from "./indexOfOrElse.js";
import { indexOfOrThrow } from "./indexOfOrThrow.js";
import { is } from "./is.js";
import { isASCII } from "./isASCII.js";
import { isEmpty } from "./isEmpty.js";
import { kebabCase } from "./kebabCase.js";
import { lastIndexOf } from "./lastIndexOf.js";
import { lastIndexOfOr } from "./lastIndexOfOr.js";
import { lastIndexOfOrElse } from "./lastIndexOfOrElse.js";
import { lastIndexOfOrThrow } from "./lastIndexOfOrThrow.js";
import { length } from "./length.js";
import { lowerCase } from "./lowerCase.js";
import { match } from "./match.js";
import { matchOr } from "./matchOr.js";
import { matchOrElse } from "./matchOrElse.js";
import { matchOrThrow } from "./matchOrThrow.js";
import { padEnd } from "./padEnd.js";
import { padStart } from "./padStart.js";
import { parseFloat } from "./parseFloat.js";
import { parseFloatOr } from "./parseFloatOr.js";
import { parseFloatOrElse } from "./parseFloatOrElse.js";
import { parseFloatOrThrow } from "./parseFloatOrThrow.js";
import { parseInt } from "./parseInt.js";
import { parseIntOr } from "./parseIntOr.js";
import { parseIntOrElse } from "./parseIntOrElse.js";
import { parseIntOrThrow } from "./parseIntOrThrow.js";
import { pascalCase } from "./pascalCase.js";
import { prepend } from "./prepend.js";
import { repeat } from "./repeat.js";
import { replace } from "./replace.js";
import { replaceAll } from "./replaceAll.js";
import { reverse } from "./reverse.js";
import { slice } from "./slice.js";
import { slugify } from "./slugify.js";
import { snakeCase } from "./snakeCase.js";
import { split } from "./split.js";
import { startsWith } from "./startsWith.js";
import { take } from "./take.js";
import { takeLast } from "./takeLast.js";
import { test } from "./test.js";
import { titleCase } from "./titleCase.js";
import { trim } from "./trim.js";
import { trimEnd } from "./trimEnd.js";
import { trimStart } from "./trimStart.js";
import { uncapitalize } from "./uncapitalize.js";
import { upperCase } from "./upperCase.js";

export const String = {
    append,
    camelCase,
    capitalize,
    constantCase,
    create,
    deburr,
    drop,
    dropLast,
    endsWith,
    graphemes,
    has,
    hasAll,
    hasAny,
    hasNone,
    indexOf,
    indexOfOr,
    indexOfOrElse,
    indexOfOrThrow,
    is,
    isASCII,
    isEmpty,
    kebabCase,
    lastIndexOf,
    lastIndexOfOr,
    lastIndexOfOrElse,
    lastIndexOfOrThrow,
    length,
    lowerCase,
    match,
    matchOr,
    matchOrElse,
    matchOrThrow,
    padEnd,
    padStart,
    parseFloat,
    parseFloatOr,
    parseFloatOrElse,
    parseFloatOrThrow,
    parseInt,
    parseIntOr,
    parseIntOrElse,
    parseIntOrThrow,
    pascalCase,
    prepend,
    repeat,
    replace,
    replaceAll,
    reverse,
    slice,
    slugify,
    snakeCase,
    split,
    startsWith,
    take,
    takeLast,
    test,
    titleCase,
    trim,
    trimEnd,
    trimStart,
    uncapitalize,
    upperCase,
}
